# Generated by Django 5.0.3 on 2024-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, choices=[('black', 'black'), ('white', 'white'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('orange', 'orange'), ('grey', 'grey')], max_length=10, null=True)),
                ('category', models.CharField(choices=[('smartphone_gadget', 'smartphone_gadget'), ('office_instrument', 'office_instrument'), ('computer_gadget', 'computer_gadget'), ('appliance_machine', 'appliance_machine'), ('kitchen_gadget', 'kitchen_gadget')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
