# Generated by Django 5.0.4 on 2024-05-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronik', '0002_rename_created_at_electronik_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronik',
            name='image',
            field=models.ImageField(default=-1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
