# Generated by Django 5.0.4 on 2024-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronik', '0004_alter_electronik_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronik',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
