# Generated by Django 5.0.4 on 2024-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronik', '0005_alter_electronik_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronik',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=9),
            preserve_default=False,
        ),
    ]
