# Generated by Django 5.0.4 on 2024-05-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronik', '0006_electronik_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronik',
            name='brand',
            field=models.CharField(choices=[('hp', 'hp'), ('acer', 'acer'), ('apple', 'apple'), ('samsung', 'samsung'), ('artel', 'artel'), ('xiomi', 'xiomi'), ('huawei', 'huawei'), ('oppo', 'oppo')], default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
