# Generated by Django 5.0.3 on 2024-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='author',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
